### PR TITLE
install protoc in gh actions

### PR DESCRIPTION
**Pull request by imor**
This PR installs the protoc compiler before running tests and clippy to avoid their failure since we now depend on it to compile the Storage Write API support.

### CODE REVIEW

**Comment by imor** [comment]
@lquerel Tests are now failing due to invalid service account key. Can you please take a look. Is  the secret `GOOGLE_APPLICATION_CREDENTIALS` up to date?

**Comment by serprex** [comment]
bit of an aside, can this feature be a feature in Cargo.toml?

**Comment by lquerel** [comment]
The other option is to "vendor" the code generated by protoc in order to remove the dependency on it, as @imor initially did. However, I still support the removal of the git submodule, which I'm not a fan of.

**Comment by lquerel** [comment]
The more I think about this latest release, the more I believe it would be simpler to eliminate this dependency on `protoc` through vendoring, as @imor initially did. I think I will go in this direction without reintroducing the git submodule.

**Comment by imor** [comment]
@lquerel It's not urgent for me. I'm ok to wait until the weekend. Thanks.

**Comment by imor** [comment]
Closing this PR as the dependency on protoc has been remove in the `main` branch.

**Pull request closed without merging**
