### PR TITLE
Allow building `Client` from `Authenticator`

### PR DESCRIPTION
**Pull request by henriiik**
Hello!

This PR makes it possible to use the `ClientBuilder` to build a `Client` with an `Authenticator`.

Currently it [is possible to create a `Client` with a custom `Authenticator` with `Client::from_authenticator`](https://github.com/lquerel/gcp-bigquery-client/blob/bd82fd16cdac389507975743478840103747e6db/src/lib.rs#L68), but then you cannot set the base_url.

### CODE REVIEW

**Comment by lquerel** [comment]
Sorry for the delay. I'm very busy these days, but I will find some time this week to review and possibly merge this contribution.

**Review by lquerel — APPROVED** [review]
KGTM. Thanks for this contribution.

**Comment by lquerel** [comment]
version 0.18.1 published on crates.io

**Comment by henriiik** [comment]
Thank you!

**Pull request merged**
