### PR TITLE
Fix tabledata.list return type

### PR DESCRIPTION
**Pull request by enricozb**
Should fix this issue: https://github.com/lquerel/gcp-bigquery-client/issues/66#issuecomment-1758752436

I didn't write any tests, but works locally with a project I am using.

### CODE REVIEW

**Comment by lquerel** [comment]
Thank you for this fix. I will publish a new version this week.

**Comment by lquerel** [comment]
Sorry but the submitted code doesn't compile. 
See: https://github.com/lquerel/gcp-bigquery-client/actions/runs/6500512333

**Comment by enricozb** [comment]
ugh sorry, let me fix that and make another PR.

**Comment by enricozb** [comment]
Fixed: https://github.com/lquerel/gcp-bigquery-client/pull/69

**Pull request merged**
