### PR TITLE
add support for bigquery AppendRows storage write API

### PR DESCRIPTION
**Pull request by imor**
NOTE: review and merge the following PR first: https://github.com/lquerel/gcp-bigquery-client/pull/94. This is because this PR's branch is cut from the previous PR's branch.

This PR adds support for [AppendRows API](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.AppendRowsRequest). It adds [googleapis repo](https://github.com/googleapis/googleapis.git) as a submodule to use .proto files from it. [prost-build](https://docs.rs/prost-build/latest/prost_build/) (via the `tonic-build` dependency) is used to compile the .proto files into Rust code. Since the storage write API is a gRPC API, [tonic](https://github.com/hyperium/tonic) is added as a dependency to use gRPC in Rust.

Partially fixes https://github.com/lquerel/gcp-bigquery-client/issues/53.

### CODE REVIEW

**Comment by lquerel** [comment]
Thank you for this contribution. I am on vacation until the beginning of next week. I will review this PR when I return.

**Review by lquerel — APPROVED** [review]
Thank you for investing the necessary time to add support for the Storage Write API, which was highly requested by the users of this crate and something I never had the time to integrate. I will just add a unit test in addition to the example you provided.

**Comment by lquerel** [comment]
I will change the way the proto files are integrated in this PR. I am not a fan of integration via git submodule as it tends to import too many things and makes contributions more complex. However, thank you again for this contribution.

**Comment by lquerel** [comment]
@imor Hi. Could you please verify on your end that the main branch is working correctly with your service account? On my side, although I think I have set the necessary permissions, I am now getting the following error when connecting to the service for the storage API (the grpc part) in the unit test present in table.rs (also true for other tests). I think it worked before, but I don’t understand what has happened in the meantime. As I don’t have much time to devote to this project at the moment, I would appreciate your help with this contribution. Thank you.

```
Error: TonicTransportError(tonic::transport::Error(Transport, ConnectError(Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) })))
```

**Comment by imor** [comment]
Thanks for spending time on this issue @lquerel, I greatly appreciate it. I have been testing this branch's code since the past few weeks and it works for me flawlessly. The error looks like a low level transport level error, so I don't think it's a service account permissions issue. The `InvalidCertificate(UnknownIssuer)` part of the error indicates the client can't verify the certificate from the server. Does the environment where you see this failure have up to date root certificates? If it's a debian based env you might need something like `apt install ca-certificates` or similar for other environments.

**Comment by fungiboletus** [comment]
I pulled the main branch and I get the same error on an up to date MacOS 14.5. However it does fail before using the storage API, so it may be unrelated to this pull request.

**Comment by fungiboletus** [comment]
Looks like the issue appears in https://github.com/lquerel/gcp-bigquery-client/commit/b0b84ecd77ebea4f39e632663d2105823c2c234d (tonic update from 0.11 to 0.12 is my guess).

**Comment by imor** [comment]
Thanks @fungiboletus for testing with an older tonic version. It turned out there was a breaking change in version 0.12. I've raised a PR to fix this: https://github.com/lquerel/gcp-bigquery-client/pull/107.

**Comment by imor** [comment]
@lquerel once that new PR is merged, it should unblock your testing and help you review #97 .

**Pull request merged**
